<?php
/**
 * BillingPaymentMethodTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Cloudpap\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CloudPap Console API
 *
 * CloudPap Console API
 *
 * OpenAPI spec version: v1
 * Contact: info@cloudpap.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.34
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Cloudpap\Client;

/**
 * BillingPaymentMethodTest Class Doc Comment
 *
 * @category    Class
 * @description BillingPaymentMethod
 * @package     Cloudpap\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BillingPaymentMethodTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BillingPaymentMethod"
     */
    public function testBillingPaymentMethod()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "added_at"
     */
    public function testPropertyAddedAt()
    {
    }

    /**
     * Test attribute "verified"
     */
    public function testPropertyVerified()
    {
    }

    /**
     * Test attribute "canceled"
     */
    public function testPropertyCanceled()
    {
    }

    /**
     * Test attribute "valid_until"
     */
    public function testPropertyValidUntil()
    {
    }

    /**
     * Test attribute "display_info"
     */
    public function testPropertyDisplayInfo()
    {
    }

    /**
     * Test attribute "card_details"
     */
    public function testPropertyCardDetails()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "token"
     */
    public function testPropertyToken()
    {
    }
}
