<?php
/**
 * CouponClaimTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CloudPap Console API
 *
 * CloudPap Console API
 *
 * OpenAPI spec version: v1
 * Contact: info@cloudpap.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.33
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CouponClaimTest Class Doc Comment
 *
 * @category    Class
 * @description CouponClaim
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CouponClaimTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CouponClaim"
     */
    public function testCouponClaim()
    {
    }

    /**
     * Test attribute "coupon_code"
     */
    public function testPropertyCouponCode()
    {
    }

    /**
     * Test attribute "billing_plan"
     */
    public function testPropertyBillingPlan()
    {
    }

    /**
     * Test attribute "backup_billing_plan"
     */
    public function testPropertyBackupBillingPlan()
    {
    }

    /**
     * Test attribute "amount_cents"
     */
    public function testPropertyAmountCents()
    {
    }

    /**
     * Test attribute "amount_cents_remaining"
     */
    public function testPropertyAmountCentsRemaining()
    {
    }

    /**
     * Test attribute "amount_currency"
     */
    public function testPropertyAmountCurrency()
    {
    }

    /**
     * Test attribute "expiration_date"
     */
    public function testPropertyExpirationDate()
    {
    }

    /**
     * Test attribute "frequency"
     */
    public function testPropertyFrequency()
    {
    }

    /**
     * Test attribute "frequency_duration"
     */
    public function testPropertyFrequencyDuration()
    {
    }

    /**
     * Test attribute "percentage_rate"
     */
    public function testPropertyPercentageRate()
    {
    }
}
