<?php
/**
 * KubeAppInstanceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CloudPap Console API
 *
 * CloudPap Console API
 *
 * OpenAPI spec version: v1
 * Contact: info@cloudpap.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * KubeAppInstanceTest Class Doc Comment
 *
 * @category    Class
 * @description KubeAppInstance
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class KubeAppInstanceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "KubeAppInstance"
     */
    public function testKubeAppInstance()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "location_country_code"
     */
    public function testPropertyLocationCountryCode()
    {
    }

    /**
     * Test attribute "version_number"
     */
    public function testPropertyVersionNumber()
    {
    }

    /**
     * Test attribute "values"
     */
    public function testPropertyValues()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "cpu"
     */
    public function testPropertyCpu()
    {
    }

    /**
     * Test attribute "memory"
     */
    public function testPropertyMemory()
    {
    }

    /**
     * Test attribute "hostname"
     */
    public function testPropertyHostname()
    {
    }

    /**
     * Test attribute "domain_connection_settings"
     */
    public function testPropertyDomainConnectionSettings()
    {
    }

    /**
     * Test attribute "has_custom_domain"
     */
    public function testPropertyHasCustomDomain()
    {
    }

    /**
     * Test attribute "cloudflare_dns_record_id"
     */
    public function testPropertyCloudflareDnsRecordId()
    {
    }

    /**
     * Test attribute "ready"
     */
    public function testPropertyReady()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "status_reason"
     */
    public function testPropertyStatusReason()
    {
    }

    /**
     * Test attribute "workload_running_percentage"
     */
    public function testPropertyWorkloadRunningPercentage()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "version"
     */
    public function testPropertyVersion()
    {
    }

    /**
     * Test attribute "tenant"
     */
    public function testPropertyTenant()
    {
    }

    /**
     * Test attribute "template"
     */
    public function testPropertyTemplate()
    {
    }

    /**
     * Test attribute "location"
     */
    public function testPropertyLocation()
    {
    }

    /**
     * Test attribute "legacy_billing_subscriptions"
     */
    public function testPropertyLegacyBillingSubscriptions()
    {
    }

    /**
     * Test attribute "billing_subscriptions"
     */
    public function testPropertyBillingSubscriptions()
    {
    }
}
