<?php
/**
 * KubeAppTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CloudPap Console API
 *
 * CloudPap Console API
 *
 * OpenAPI spec version: v1
 * Contact: info@cloudpap.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * KubeAppTest Class Doc Comment
 *
 * @category    Class
 * @description KubeApp
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class KubeAppTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "KubeApp"
     */
    public function testKubeApp()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "icon"
     */
    public function testPropertyIcon()
    {
    }

    /**
     * Test attribute "helm_repo_url"
     */
    public function testPropertyHelmRepoUrl()
    {
    }

    /**
     * Test attribute "helm_repo_name"
     */
    public function testPropertyHelmRepoName()
    {
    }

    /**
     * Test attribute "helm_package_name"
     */
    public function testPropertyHelmPackageName()
    {
    }

    /**
     * Test attribute "enabled"
     */
    public function testPropertyEnabled()
    {
    }

    /**
     * Test attribute "cluster"
     */
    public function testPropertyCluster()
    {
    }

    /**
     * Test attribute "templates"
     */
    public function testPropertyTemplates()
    {
    }
}
