<?php
/**
 * KubeAppVersionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CloudPap Console API
 *
 * CloudPap Console API
 *
 * OpenAPI spec version: v1
 * Contact: info@cloudpap.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * KubeAppVersionTest Class Doc Comment
 *
 * @category    Class
 * @description KubeAppVersion
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class KubeAppVersionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "KubeAppVersion"
     */
    public function testKubeAppVersion()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "version"
     */
    public function testPropertyVersion()
    {
    }

    /**
     * Test attribute "helm_chart_version"
     */
    public function testPropertyHelmChartVersion()
    {
    }

    /**
     * Test attribute "default_values"
     */
    public function testPropertyDefaultValues()
    {
    }

    /**
     * Test attribute "enabled"
     */
    public function testPropertyEnabled()
    {
    }

    /**
     * Test attribute "override_values_schema"
     */
    public function testPropertyOverrideValuesSchema()
    {
    }

    /**
     * Test attribute "values_schema"
     */
    public function testPropertyValuesSchema()
    {
    }

    /**
     * Test attribute "credentials_mapping"
     */
    public function testPropertyCredentialsMapping()
    {
    }

    /**
     * Test attribute "kube_app"
     */
    public function testPropertyKubeApp()
    {
    }
}
