<?php
/**
 * VirtualMachineImageTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CloudPap Console API
 *
 * CloudPap Console API
 *
 * OpenAPI spec version: v1
 * Contact: info@cloudpap.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * VirtualMachineImageTest Class Doc Comment
 *
 * @category    Class
 * @description VirtualMachineImage
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class VirtualMachineImageTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "VirtualMachineImage"
     */
    public function testVirtualMachineImage()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "uid"
     */
    public function testPropertyUid()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "os_type"
     */
    public function testPropertyOsType()
    {
    }

    /**
     * Test attribute "os_version"
     */
    public function testPropertyOsVersion()
    {
    }

    /**
     * Test attribute "default_root_user"
     */
    public function testPropertyDefaultRootUser()
    {
    }

    /**
     * Test attribute "network_card_name"
     */
    public function testPropertyNetworkCardName()
    {
    }

    /**
     * Test attribute "gateway_on_network_data"
     */
    public function testPropertyGatewayOnNetworkData()
    {
    }

    /**
     * Test attribute "additional_runcmd"
     */
    public function testPropertyAdditionalRuncmd()
    {
    }

    /**
     * Test attribute "additional_bootcmd"
     */
    public function testPropertyAdditionalBootcmd()
    {
    }

    /**
     * Test attribute "additional_packages"
     */
    public function testPropertyAdditionalPackages()
    {
    }
}
