<?php
/**
 * KubeAppsInstancesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CloudPap Console API
 *
 * CloudPap Console API
 *
 * OpenAPI spec version: v1
 * Contact: info@cloudpap.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * KubeAppsInstancesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class KubeAppsInstancesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for kubeAppsInstancesConnectDomain
     *
     * .
     *
     */
    public function testKubeAppsInstancesConnectDomain()
    {
    }

    /**
     * Test case for kubeAppsInstancesCreate
     *
     * .
     *
     */
    public function testKubeAppsInstancesCreate()
    {
    }

    /**
     * Test case for kubeAppsInstancesDelete
     *
     * .
     *
     */
    public function testKubeAppsInstancesDelete()
    {
    }

    /**
     * Test case for kubeAppsInstancesList
     *
     * .
     *
     */
    public function testKubeAppsInstancesList()
    {
    }

    /**
     * Test case for kubeAppsInstancesPartialUpdate
     *
     * .
     *
     */
    public function testKubeAppsInstancesPartialUpdate()
    {
    }

    /**
     * Test case for kubeAppsInstancesRead
     *
     * .
     *
     */
    public function testKubeAppsInstancesRead()
    {
    }

    /**
     * Test case for kubeAppsInstancesUpdate
     *
     * .
     *
     */
    public function testKubeAppsInstancesUpdate()
    {
    }
}
