<?php
/**
 * VirtualMachinesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CloudPap Console API
 *
 * CloudPap Console API
 *
 * OpenAPI spec version: v1
 * Contact: info@cloudpap.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * VirtualMachinesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class VirtualMachinesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for virtualMachinesChangeVmBackupTemplate
     *
     * .
     *
     */
    public function testVirtualMachinesChangeVmBackupTemplate()
    {
    }

    /**
     * Test case for virtualMachinesChangeVmTemplate
     *
     * .
     *
     */
    public function testVirtualMachinesChangeVmTemplate()
    {
    }

    /**
     * Test case for virtualMachinesCreate
     *
     * .
     *
     */
    public function testVirtualMachinesCreate()
    {
    }

    /**
     * Test case for virtualMachinesDelete
     *
     * .
     *
     */
    public function testVirtualMachinesDelete()
    {
    }

    /**
     * Test case for virtualMachinesDisableVmBackup
     *
     * .
     *
     */
    public function testVirtualMachinesDisableVmBackup()
    {
    }

    /**
     * Test case for virtualMachinesList
     *
     * .
     *
     */
    public function testVirtualMachinesList()
    {
    }

    /**
     * Test case for virtualMachinesPartialUpdate
     *
     * .
     *
     */
    public function testVirtualMachinesPartialUpdate()
    {
    }

    /**
     * Test case for virtualMachinesPauseVm
     *
     * .
     *
     */
    public function testVirtualMachinesPauseVm()
    {
    }

    /**
     * Test case for virtualMachinesRead
     *
     * .
     *
     */
    public function testVirtualMachinesRead()
    {
    }

    /**
     * Test case for virtualMachinesRebuildVm
     *
     * .
     *
     */
    public function testVirtualMachinesRebuildVm()
    {
    }

    /**
     * Test case for virtualMachinesRestartVm
     *
     * .
     *
     */
    public function testVirtualMachinesRestartVm()
    {
    }

    /**
     * Test case for virtualMachinesSoftRebootVm
     *
     * .
     *
     */
    public function testVirtualMachinesSoftRebootVm()
    {
    }

    /**
     * Test case for virtualMachinesStartVm
     *
     * .
     *
     */
    public function testVirtualMachinesStartVm()
    {
    }

    /**
     * Test case for virtualMachinesStopVm
     *
     * .
     *
     */
    public function testVirtualMachinesStopVm()
    {
    }

    /**
     * Test case for virtualMachinesTakeVmBackup
     *
     * .
     *
     */
    public function testVirtualMachinesTakeVmBackup()
    {
    }

    /**
     * Test case for virtualMachinesTakeVmSnapshot
     *
     * .
     *
     */
    public function testVirtualMachinesTakeVmSnapshot()
    {
    }

    /**
     * Test case for virtualMachinesUnpauseVm
     *
     * .
     *
     */
    public function testVirtualMachinesUnpauseVm()
    {
    }

    /**
     * Test case for virtualMachinesUpdate
     *
     * .
     *
     */
    public function testVirtualMachinesUpdate()
    {
    }
}
